Pinder/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pinderApp.urls')),
]

pinderApp/urls.py
from django.urls import path
from pinderApp import views
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView,LogoutView

urlpatterns = [
    path('', views.landing, name="inicio"),
    path("about", views.about, name="about"),
    ##HOME URL
    path('feed', views.feed, name="feed"),
    ##PROFILE URL
    path('profile/', views.profile, name='profile'),
	path('profile/<str:username>', views.profile, name='profile'),
    path("edit", views.editProfile, name="update_profile"),
    ## PROFILE USER FOLLOWERS URL
    path('profile/<str:username>/follow', views.follow, name='follow'),
	path('profile/<str:username>/unfollow', views.unfollow, name='unfollow'),
    ##POST URL
    path("post", views.post, name="post"),
    path("post/<int:pk>",PostDetailView.as_view(), name='post_detail'),
    path("post/<int:pk>/like",AddLike.as_view(), name='like'),   
    path('post/<int:pk>/dislike', AddDislike.as_view(), name='dislike'),
    path("post/edit/<int:pk>",PostEditView.as_view(), name='post_edit'),
    path("post/delete/<int:pk>",PostDeleteView.as_view(), name='post_delete'),
    ##POST COMMENT URL
    path('post/<int:post_pk>/comment/delete/<int:pk>/', CommentDeleteView.as_view(), name="comment_delete"),
    path('post/<int:post_pk>/comment/edit/<int:pk>/', CommentEditView.as_view(), name="comment_edit"), 
    ##FILTER URL
    path('gatos', views.gatos, name="gatos"),
    path('perros', views.perros, name="perros"),
    ##LOGIN,REGISTER,LOGOUT URL
    path('register', views.register, name="register"),
    path('login',LoginView.as_view(template_name="pinderApp/login.html"), name="login"),
    path('logout',LogoutView.as_view(template_name="pinderApp/logout.html"), name="logout"),
    ## SEARCHBAR
    path('search',views.searchbox,name="search"),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

pinderApp/models.py
from email.mime import image
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

# MODELO DE PERFIL DEL USUARIO
SEXO_USUARIO = (
    ("1", "Masculino"),
    ("2", "Femenino"),
    ("3", "Prefiero no decirlo")
)

ESPACIO_USUARIO = (
    ("1", "Patio o Parque"),
    ("2", "Terraza o Balcon"),
    ("3", "No poseo"),
)


class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile_pics',
                              default='../media/user.png')
    dni = models.PositiveIntegerField(null=True)
    sexo = models.CharField(
        max_length=30,
        choices=SEXO_USUARIO
    )
    edad = models.PositiveIntegerField(null=True)
    telefono = models.PositiveIntegerField(null=True)
    localidad = models.CharField(max_length=50)
    provincia = models.CharField(max_length=30)
    ocupacion = models.CharField(max_length=50)
    carga_horaria = models.PositiveIntegerField(null=True)
    dias_homeoffice = models.PositiveIntegerField(null=True)
    cantidad_hijos = models.PositiveIntegerField(null=True)
    cantidad_mascotas = models.PositiveIntegerField(null=True)
    especie_mascota = models.CharField(max_length=50)
    espacio_abierto = models.CharField(
        max_length=40,
        choices=ESPACIO_USUARIO
    )
    ig = models.URLField(null=True)
    fb = models.URLField(null=True)
    tw = models.URLField(null=True)

    def following(self):
        user_ids = Relationship.objects.filter(from_user=self.user)\
            .values_list('to_user_id', flat=True)
        return User.objects.filter(id__in=user_ids)

    def followers(self):
        user_ids = Relationship.objects.filter(to_user=self.user)\
        .values_list('from_user_id', flat=True)
        return User.objects.filter(id__in=user_ids)

    def __str__(self):
	    return f'Perfil de {self.user.username}'



# POSTEO DE ANIMAL
ESPECIE_OPCIONES = (
    ("1", "Perro"),
    ("2", "Gato"),
)

SEXO_OPCIONES = (
    ("1", "Macho"),
    ("2", "Hembra"),
)

TAMANIO_OPCIONES = (
("1", "Grande"),
("2", "Mediano"),
("3", "Chico"),
)

CASTRACION_OPCIONES = (
    ("1", "Si"),
    ("2", "No"),
)

DESPARASITADO_OPCIONES = (
    ("1", "Si"),
    ("2", "No"),
)

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posteos') 
    likes = models.ManyToManyField(User,blank=True, related_name='likes')
    dislikes = models.ManyToManyField(User,blank=True, related_name='dislikes')
    timestamp = models.DateTimeField(default=timezone.now)
    nombre = models.CharField(max_length=30, blank=True,null=True)
    especie = models.CharField(
        max_length=20,
        choices=ESPECIE_OPCIONES,
        default="Elegir Opcion"

          )
    sexo = models.CharField(
        max_length=20,
        choices=SEXO_OPCIONES, 
        default="Elegir Opcion"

    )
    edad = models.PositiveIntegerField(blank=True,null=True)
    tamanio = models.CharField(
        max_length=20,
        choices=TAMANIO_OPCIONES,
        default="Elegir Opcion"

    )
    vacunas_aplicadas = models.PositiveIntegerField(blank=True,null=True)
    castracion = models.CharField(
        max_length=20,
        choices=CASTRACION_OPCIONES, 
        default="Elegir Opcion"

    )
    desparasitado = models.CharField(
        max_length=20,
        choices=DESPARASITADO_OPCIONES,
        default="Elegir Opcion"
    )
    discapacidad = models.CharField(max_length=150, blank=True)
    content = models.TextField(max_length=500)
    image = models.ImageField(upload_to='posteos', null=True)    

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return f'{self.user.username}: {self.content}'


class PostComment(models.Model):
    comment = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_posteos') 
    timestamp = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey(Post, on_delete=models.CASCADE,  blank=True, null=True,)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='+')

    @property
    def children(self):
        return Post.objects.filter(parent=self).order_by('-timestamp').all()

    @property
    def is_parent(self):
        if self.parent is None:
            return True
        return False


    
class Relationship(models.Model):
	from_user = models.ForeignKey(User, related_name='relationships', on_delete=models.CASCADE)
	to_user = models.ForeignKey(User, related_name='related_to', on_delete=models.CASCADE)

	def __str__(self):
		return f'{self.from_user} to {self.to_user}'

	class Meta:
		indexes = [
		models.Index(fields=['from_user', 'to_user',]),
		]

pinderApp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.urls import  reverse_lazy
from django.views import View
from .models import *
from .forms import *
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.generic.edit import UpdateView,DeleteView
from django.db.models import Q

# Create your views here.


def landing(request):
    return render(request, "pinderApp/index.html")

def about(request):
    return render(request, "pinderApp/about.html")


@login_required
def searchbox(request):
    search = request.GET['search']
    usersearch = User.objects.filter(username__icontains=search)
    if usersearch:
         context={
             'search':search,
             'usersearch':usersearch,
         }
         messages.success(request, 'Resultados encontrados con exito')
         return  render(request,"pinderApp/search.html",context)
    else:
     messages.error(request, 'No se encontro')
     return redirect('feed')

    


@login_required
def feed(request):

  data = Post.objects.all()
  context = {'data': data}
  return render(request, "pinderApp/feed.html", context)

@login_required
def post(request):
    current_user = get_object_or_404(User, pk=request.user.pk)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = current_user
            post.save()
            messages.success(request, 'Post creado con exito.')
            return redirect('feed')
    else:
        form = PostForm()
    return render(request, "pinderApp/post.html", {'form': form})

@login_required
def profile(request, username=None):
    current_user = request.user
    if username and username != current_user.username:
     user = User.objects.get(username=username)
     posteos = user.posteos.all()
    else:
     posteos = current_user.posteos.all()
     user = current_user

    context= {
        'user':user,
        'posteos':posteos,
        }        
              
    return render(request, 'pinderApp/profile.html', context)

@login_required
def follow(request,username):
    current_user = request.user
    to_user = User.objects.get(username=username)
    to_user_id = to_user
    rel = Relationship(from_user=current_user, to_user=to_user_id)
    rel.save()
    messages.success(request, f'Siguiendo a {username}')
    return redirect('profile', username=to_user)

@login_required
def unfollow(request, username):
	current_user = request.user
	to_user = User.objects.get(username=username)
	to_user_id = to_user.id
	rel = Relationship.objects.filter(from_user=current_user.id, to_user=to_user_id).get()
	rel.delete()
	messages.success(request, f'Ya no sigues a {username}')
	return redirect('profile', username=to_user)

@login_required
def followersList(request, username):
    user = User.objects.get(username=username)
    follows = user.followers.all()
    context= {
        'user':user,
        'follows':follows
        }      
    return render(request, 'pinderApp/followers_list.html', context)

@login_required
def editProfile(request):
    user = request.user.id
    profile = Profile.objects.get(user__id=user)
    user__basic__info = User.objects.get(id=user)

    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, request.FILES , instance=profile)
        if form.is_valid():
          user__basic__info.first_name= form.cleaned_data.get('first_name')
          user__basic__info.last_name= form.cleaned_data.get('last_name') 
          user__basic__info.username= form.cleaned_data.get('username') 
          user__basic__info.email= form.cleaned_data.get('email') 
          
          profile.image = form.cleaned_data.get('image')
          profile.dni = form.cleaned_data.get('dni')
          profile.sexo = form.cleaned_data.get('sexo')
          profile.edad = form.cleaned_data.get('edad')
          profile.telefono = form.cleaned_data.get('telefono')
          profile.localidad = form.cleaned_data.get('localidad')
          profile.provincia = form.cleaned_data.get('provincia')
          profile.ocupacion = form.cleaned_data.get('ocupacion')
          profile.carga_horaria = form.cleaned_data.get('carga_horaria')
          profile.dias_homeoffice = form.cleaned_data.get('dias_homeoffice')
          profile.cantidad_hijos = form.cleaned_data.get('cantidad_hijos')
          profile.espacio_abierto = form.cleaned_data.get('espacio_abierto')
          profile.ig = form.cleaned_data.get('ig')
          profile.fb = form.cleaned_data.get('fb')
          profile.tw = form.cleaned_data.get('tw')


          profile.save()
          user__basic__info.save()
          messages.success(request, f'Perfil actualizado con exito.')
          return redirect('profile', username=request.user.username)
    else:
        form = ProfileUpdateForm(instance=profile)
    
    context={
      'form':form,
    } 
    return render(request, "pinderApp/profile_form.html", context)

@login_required
def gatos(request):
    cat = Post.objects.filter(especie='2')
    context = {'cat':cat}
    return render(request, 'pinderApp/gatos.html',context)

@login_required
def perros(request):
    dog = Post.objects.filter(especie='1')
    context = { 'dog':dog}
    return render(request, 'pinderApp/perros.html',context)    

def register(request):
    if request.user.is_authenticated:
        return redirect('feed')
    else:
        if request.method == 'POST':
         form = UserRegisterForm(request.POST)
         if form.is_valid():
             form.save()
             user = form.cleaned_data.get('username')
             password = form.cleaned_data.get('password1')
             username = authenticate(username=user, password=password)
             login(request, username)
             messages.success( request, f'Hola {user}, tu usuario se creo con exito.')
             return redirect('feed')
        else:
          form = UserRegisterForm()
          context = {'form': form}
          return render(request, "pinderApp/register.html", context)    

class PostDetailView(View,LoginRequiredMixin):
    def get(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        form = PostCommentForm()

        comments = PostComment.objects.filter(post=post).order_by('-timestamp')

        context = {
            'post': post,
            'form': form,
            'comments':comments
        }
 
        return render(request,'pinderApp/post_detail.html', context)

    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        form = PostCommentForm(request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.save()

        comments = PostComment.objects.filter(post=post).order_by('-timestamp')
    
        context ={
           'post':post,
           'form':form,
           'comments':comments,
        }   
        return render(request,'pinderApp/post_detail.html',context)
    
class PostEditView(UpdateView ,LoginRequiredMixin,UserPassesTestMixin):
    model=Post
    fields='__all__'
    template_name= 'pinderApp/post_edit.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('post_detail', kwargs={'pk':pk})

    def test_func(self):
        post = self.ger_object()
        return self.request.user == post.author  

class PostDeleteView(DeleteView ,LoginRequiredMixin,UserPassesTestMixin):
    model=Post
    fields='__all__'
    template_name= 'pinderApp/post_delete.html'
    success_url = reverse_lazy('feed')

    def test_func(self):
        post = self.ger_object()
        return self.request.user == post.author  

class AddLike(LoginRequiredMixin,View):
    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)

        is_like = False
        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if not is_like:
            post.likes.add(request.user)

        if is_like:
            post.likes.remove(request.user)    

        next = request.POST.get('next','/')
        return HttpResponseRedirect(next)    

class AddDislike(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)

        is_like = False

        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if is_like:
            post.likes.remove(request.user)

        is_dislike = False
        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if not is_dislike:
            post.dislikes.add(request.user)

        if is_dislike:
            post.dislikes.remove(request.user)

        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)

class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model=PostComment
    template_name="pinderApp/comment_delete.html"

    def get_success_url(self):
        pk = self.kwargs['post_pk']
        return reverse_lazy('post_detail', kwargs={'pk': pk})

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

class CommentEditView(UpdateView ,LoginRequiredMixin,UserPassesTestMixin):
    model = PostComment
    fields = ['comment']
    template_name = 'pinderApp/comment_edit.html'

    def get_success_url(self):
        pk = self.kwargs['post_pk']

pinderApp/templates/pinderApp/comment_delete.html
{% extends 'pinderApp/layout.html' %}
{% block title %}Borrar commentario {{post.nombre}}{% endblock title %}
{% block content %}

<article class="postear container">
    <form method="post" enctype="multipart/form-data" class="form-delete">
        {% csrf_token %}
       
        <h2>BORRAR COMENTARIO!</h2>
        <p>¿Esta seguro de eliminar el comentario?</p>
        <div class="article-delete">
            <a href="{% url 'feed'%}" class="btn">Cancelar</a>
            <button type="submit" class="btn--form btn">Borrar!</button>
        </div>
    </form>
   
</article>

{% endblock %}

pinderApp/templates/pinderApp/comment_edit.html
{% extends 'pinderApp/layout.html' %}
{% block title %}Editar comentario {% endblock title %}
{% block content %}

<article class="postear">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
       {{form}}
        <button type="submit" class="btn--form">Actualizar Comentario!</button>
    </form>
   
</article>

{% endblock %}

pinderApp/templates/pinderApp/gatos.html
{% extends 'pinderApp/feed.html' %}
{% block title %}Gatos{% endblock title %}
{% load humanize %}

{% block content %}


{% for d in cat %}

<article class="posteo">
    {% if d.image %}
    <img src="{{ d.image.url}}"  class="posteo__img">
    {% endif%}
    <div class="posteo__info">
         <div class="posteo__info--head">
            <div class="posteo__info--head-r">
            {% if d.author.profile.image.url %}
            <img src="{{ d.author.profile.image.url}}" alt="{{d.author.username}}">
            {% else %} 
            <img src="../../static/pinderApp/assets/user.png" alt="{{d.author.username}}">
            {% endif %}
            <div class="posteo__info--head-content">
                <h2>{{d.author.first_name}} {{d.author.last_name}}</h2>
               <a href="{% url 'profile' d.author.username %}">@{{d.author.username}}</a>   
               <time data-time="#"> <i class="bi bi-clock-history"> Publicado:  </i> {{d.timestamp|naturaltime}}</time>
            </div> 
            </div>
            <div class="btn-group">
                <button class="btn btn-feed dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="bi bi-three-dots"></i>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <li><a class="dropdown-item" href="#">Eliminar</a></li>
                  <li><a class="dropdown-item" href="#">Editar</a></li>
                </ul>
              </div>
         </div>  
        <div class="posteo__info__content">
            <h5>Nombre de mascota: {{d.nombre}}</h5>
            <ul>
                <li>Informacion de la mascota:</li>
                <li>{{d.get_especie_display}}</li>
                <li>Edad: {{d.edad}}</li>
            </ul>
            <p>{{d.content}}</p>
        </div>
        <div class="posteo__feed-btn">
            <a href="">Ver Posteo</a>
        </div>
    </div>
</article>

{% endfor %}



{% endblock %}

pinderApp/templates/pinderApp/login.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!---- Favicon-->
    <link rel="shortcut icon" href="{% static 'pinderApp/assets/favicon.ico' %}">
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- CSS -->
    <link href="{% static 'pinderApp/css/style.css' %}" rel="stylesheet" />
    <title>Iniciar Sesion</title>
</head>

<body class="bg-app ">

    <main class="form-contenedor">
        <section class="formulario">

            <h1>Iniciar <span>sesion</span></h1>
      <p class="formulario__head">¿No tienes cuenta? <a href="{% url 'register' %}" >Registrarse</a></p>
            <form class="formulario__content container" method="post">
                {% csrf_token %}
                {{form}}
            
                <button type="submit" id="submit" class="btn--form btn-landing">Iniciar sesion</button>
            
            </form>

        </section>
        <section class="form__carousel">
            <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img src="{% static 'pinderApp/assets/car2.jpg' %}" class="d-block w-100" alt="michi con estilo">
                  </div>
                  <div class="carousel-item">
                    <img src="{% static 'pinderApp/assets/car1.jpg' %}" class="d-block w-100" alt="perrito amarillo">
                  </div>
                  <div class="carousel-item">
                    <img src="{% static 'pinderApp/assets/car3.jpg' %}" class="d-block w-100" alt="perrito con rosas">
                  </div>
                </div>
              </div>
            
        </section>
    </main>







    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
</body>

</html>

pinderApp/templates/pinderApp/post.html
{% extends 'pinderApp/layout.html' %}
{% block title %}Crear Post{% endblock title %}
{% block content %}

<article class="postear">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
       {{form}}
        <button type="submit" class="btn--form">Crear Post!</button>
    </form>
   
</article>

{% endblock %}

pinderApp/templates/pinderApp/post_delete.html
{% extends 'pinderApp/layout.html' %}
{% block title %}Borrar post {{post.nombre}}{% endblock title %}
{% block content %}

<article class="postear container">
    <form method="post" enctype="multipart/form-data" class="form-delete">
        {% csrf_token %}
       
        <h2>BORRAR POST!</h2>
        <p>¿Esta seguro de eliminar el post?</p>
        <div class="article-delete">
            <a href="{% url 'feed'%}" class="btn">Cancelar</a>
            <button type="submit" class="btn--form btn">Borrar Post! </button>
        </div>
    </form>
   
</article>

{% endblock %}

pinderApp/templates/pinderApp/post_detail.html
{% extends 'pinderApp/layout.html' %}
{% block title %}Post de {{post.nombre}}{% endblock title %}
{% load humanize %}
{% block content %}

<article class="posteo__detail">
       <div class="posteo__info--head-detail">
            <div class="posteo__info--head-r detail-user-img">
                {% if post.author.profile.image.url %}
                <img src="{{ post.author.profile.image.url}}" alt="{{post.author.username}}" class="">
                {% else %} 
                <img src="../../static/pinderApp/assets/user.png" alt="{{post.author.username}}">
                {% endif %}
                <div class="posteo__info--head-content">
                  <h2>{{post.author.first_name}} {{post.author.last_name}}</h2>
                  <time data-time="#"> <i class="bi bi-clock-history"> Publicado: </i> {{post.timestamp|naturaltime}} por: <a href="{% url 'profile' post.author %}"> @{{post.author}}</a>   </time>
                </div> 
             </div>
             {% if request.user == post.author %}
             <div class="btn-group">
                  <button class="btn btn-feed dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="bi bi-three-dots"></i>
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <li><a class="dropdown-item" href="{% url 'post_edit' post.pk %}">Editar</a></li>
                      <li><a class="dropdown-item" href="{% url 'post_delete' post.pk %}">Eliminar</a></li>
                  </ul>
             </div>
             {% endif %}
       </div>  
    <img src="{{ post.image.url}}"  class="posteo__img">
    <div class="posteo__info-detail">
        
        <div class="posteo__info__content--detail">
            <h3>Nombre de mascota:</h3>
            <p class="post__detail-title">{{post.nombre}}</p>
            <ul>
                <li>Informacion de la mascota:</li>
                <li><span class="span__detail"> Especie: </span> {{post.get_especie_display}}</li>
                <li><span class="span__detail"> Edad: </span> {{post.edad}}</li>
                <li><span class="span__detail"> Sexo: </span> {{post.get_sexo_display}}</li>
                <li><span class="span__detail"> Tamaño:</span>  {{post.get_tamanio_display}}</li>
                <li><span class="span__detail"> Vacunas aplicadas: </span> {{post.vacunas_aplicadas}}</li>
                <li><span class="span__detail"> ¿Esta castrado?:</span>  {{post.get_castracion_display}}</li>
                <li><span class="span__detail"> ¿Esta desparacitado?: </span> {{post.get_desparasitado_display}}</li>
                <li><span class="span__detail"> Discapacidad: </span>  {{post.discapacidad}}</li>
            </ul>
            <h4>Descripcion:</h4>
            <p class="post__detail-descripcion">{{post.content}}</p>
            <div class="post__detail--react">

              {% if post.likes %}
              <span class=""> {{post.likes.all.count}} <i class="bi bi-heart-fill"></i> </span>
              {% else %}
              <span class=""> 0 <i class="bi bi-heart"></i> </span>
              {% endif %}
                <form method="POST" action="{% url 'like' post.pk %}">
                   {% csrf_token %}
                   <input type="hidden" name="next" value={{request.path}}>
                   <button type="submit">
                    Me gusta
                   </button>     
                </form>

            </div>
        </div>
         
    </div>
</article>

<article class="comments">
  <div class="posteo__comments">
    {% if comments %}
    {% for comment in comments %}
    <div class="comments__author">
      <div class="posteo__info--head-detail">
        <div class="posteo__info--head-r detail-user-img">
          <a href="{% url 'profile' comment.author %}">
            {% if comment.author.profile.image.url %}
            <img src="{{ comment.author.profile.image.url}}" alt="{{comment.author.username}}" class="">
            {% else %} 
            <img src="../../static/pinderApp/assets/user.png" alt="{{comment.author.username}}">
            {% endif %}
          </a>   
        <div class="posteo__info--head-content">
            <h2>{{comment.author.first_name}} {{comment.author.last_name}}</h2>
            <time data-time="#"> <i class="bi bi-clock-history"></i> {{comment.timestamp|naturaltime}} por: <a href="{% url 'profile' comment.author %}"> @{{comment.author}}</a>   </time>
          
        </div> 
        </div>
     </div>  
     <div class="comments__contenido">
      <p>
        {{comment.comment}}
       </p>
       <div class="comments__contenido-btn">
       {% if request.user == comment.author %}
        <a href="{% url 'comment_edit' post.pk comment.pk %}">Editar</a>
        <a href="{% url 'comment_delete' post.pk comment.pk %}">Eliminar</a>
       {% endif %}
      </div>
     </div>
    </div>
    {% endfor %} 
    {% else %}
    <h2>Aun no hay comentarios, se el primero.</h2>
    {% endif %} 
  </div>
  <div class="posteo__coments-create">
    <form action="" method="POST">
      {% csrf_token %}
      {{form.comment}}
      <button type="submit" class="btn-comment">Comentar</button>
    </form>
   </div>
</article>

{% endblock %}

pinderApp/templates/pinderApp/post_edit.html
{% extends 'pinderApp/layout.html' %}
{% block title %}Editar Post {{post.nombre}}{% endblock title %}
{% block content %}

<article class="postear">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
       {{form}}
        <button type="submit" class="btn--form">Actualizar Post!</button>
    </form>
   
</article>

{% endblock %}